// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/neuroevolution.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/neuroevolution.proto

It has these top-level messages:
	Individual
	Evaluation
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Individual is a sequence of random seeds used to generate a candidate network.
type Individual struct {
	Seeds []uint64 `protobuf:"varint,1,rep,packed,name=seeds" json:"seeds,omitempty"`
}

func (m *Individual) Reset()                    { *m = Individual{} }
func (m *Individual) String() string            { return proto1.CompactTextString(m) }
func (*Individual) ProtoMessage()               {}
func (*Individual) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Individual) GetSeeds() []uint64 {
	if m != nil {
		return m.Seeds
	}
	return nil
}

// Evaluation is an individual and the score that indivual achieved.
type Evaluation struct {
	Individual *Individual `protobuf:"bytes,1,opt,name=individual" json:"individual,omitempty"`
	Score      float32     `protobuf:"fixed32,2,opt,name=score" json:"score,omitempty"`
}

func (m *Evaluation) Reset()                    { *m = Evaluation{} }
func (m *Evaluation) String() string            { return proto1.CompactTextString(m) }
func (*Evaluation) ProtoMessage()               {}
func (*Evaluation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Evaluation) GetIndividual() *Individual {
	if m != nil {
		return m.Individual
	}
	return nil
}

func (m *Evaluation) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto1.RegisterType((*Individual)(nil), "neuroevolution.Individual")
	proto1.RegisterType((*Evaluation)(nil), "neuroevolution.Evaluation")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Neuro service

type NeuroClient interface {
	// Seek returns a new individual to test.
	Seek(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Individual, error)
	// Show shows the performance of an individual to the server.
	Show(ctx context.Context, in *Evaluation, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type neuroClient struct {
	cc *grpc.ClientConn
}

func NewNeuroClient(cc *grpc.ClientConn) NeuroClient {
	return &neuroClient{cc}
}

func (c *neuroClient) Seek(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Individual, error) {
	out := new(Individual)
	err := grpc.Invoke(ctx, "/neuroevolution.Neuro/Seek", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neuroClient) Show(ctx context.Context, in *Evaluation, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/neuroevolution.Neuro/Show", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Neuro service

type NeuroServer interface {
	// Seek returns a new individual to test.
	Seek(context.Context, *google_protobuf.Empty) (*Individual, error)
	// Show shows the performance of an individual to the server.
	Show(context.Context, *Evaluation) (*google_protobuf.Empty, error)
}

func RegisterNeuroServer(s *grpc.Server, srv NeuroServer) {
	s.RegisterService(&_Neuro_serviceDesc, srv)
}

func _Neuro_Seek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NeuroServer).Seek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/neuroevolution.Neuro/Seek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NeuroServer).Seek(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neuro_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Evaluation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NeuroServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/neuroevolution.Neuro/Show",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NeuroServer).Show(ctx, req.(*Evaluation))
	}
	return interceptor(ctx, in, info, handler)
}

var _Neuro_serviceDesc = grpc.ServiceDesc{
	ServiceName: "neuroevolution.Neuro",
	HandlerType: (*NeuroServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Seek",
			Handler:    _Neuro_Seek_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _Neuro_Show_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/neuroevolution.proto",
}

func init() { proto1.RegisterFile("proto/neuroevolution.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4b, 0x2d, 0x2d, 0xca, 0x4f, 0x2d, 0xcb, 0xcf, 0x29, 0x2d, 0xc9, 0xcc, 0xcf,
	0xd3, 0x03, 0x0b, 0x0a, 0xf1, 0xa1, 0x8a, 0x4a, 0x49, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea,
	0x83, 0x65, 0x93, 0x4a, 0xd3, 0xf4, 0x53, 0x73, 0x0b, 0x4a, 0x2a, 0x21, 0x8a, 0x95, 0x94, 0xb8,
	0xb8, 0x3c, 0xf3, 0x52, 0x32, 0xcb, 0x32, 0x53, 0x4a, 0x13, 0x73, 0x84, 0x44, 0xb8, 0x58, 0x8b,
	0x53, 0x53, 0x53, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0x58, 0x82, 0x20, 0x1c, 0xa5, 0x38, 0x2e,
	0x2e, 0xd7, 0xb2, 0xc4, 0x9c, 0xd2, 0x44, 0x90, 0x71, 0x42, 0x56, 0x5c, 0x5c, 0x99, 0x70, 0x1d,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x52, 0x7a, 0x68, 0x2e, 0x41, 0x98, 0x19, 0x84, 0xa4,
	0x1a, 0x6c, 0x7e, 0x72, 0x7e, 0x51, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x53, 0x10, 0x84, 0x63,
	0xd4, 0xcc, 0xc8, 0xc5, 0xea, 0x07, 0xd2, 0x2f, 0x64, 0xc3, 0xc5, 0x12, 0x9c, 0x9a, 0x9a, 0x2d,
	0x24, 0xa6, 0x07, 0x71, 0xb3, 0x1e, 0xcc, 0xcd, 0x7a, 0xae, 0x20, 0x37, 0x4b, 0xe1, 0xb1, 0x47,
	0x89, 0x01, 0xac, 0x3b, 0x23, 0xbf, 0x5c, 0x08, 0x43, 0x15, 0xc2, 0xf5, 0x52, 0x38, 0x4c, 0x56,
	0x62, 0x70, 0x62, 0x8f, 0x62, 0x85, 0x88, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x55, 0x8a, 0x60, 0x2a, 0x64, 0x01, 0x00, 0x00,
}
