# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import neuroevolution_pb2 as proto_dot_neuroevolution__pb2


class NeuroStub(object):
  """Neuro service exposes basic genetic algorithm for neuro-evolution.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Seek = channel.unary_unary(
        '/neuroevolution.Neuro/Seek',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_neuroevolution__pb2.Individual.FromString,
        )
    self.Show = channel.unary_unary(
        '/neuroevolution.Neuro/Show',
        request_serializer=proto_dot_neuroevolution__pb2.Evaluation.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class NeuroServicer(object):
  """Neuro service exposes basic genetic algorithm for neuro-evolution.
  """

  def Seek(self, request, context):
    """Seek returns a new individual to test.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Show(self, request, context):
    """Show shows the performance of an individual to the server.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NeuroServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Seek': grpc.unary_unary_rpc_method_handler(
          servicer.Seek,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=proto_dot_neuroevolution__pb2.Individual.SerializeToString,
      ),
      'Show': grpc.unary_unary_rpc_method_handler(
          servicer.Show,
          request_deserializer=proto_dot_neuroevolution__pb2.Evaluation.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'neuroevolution.Neuro', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
